tsr-docusign/main/default/objects/Docusign_Access_Token__c/Docusign_Access_Token__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores docusign access token</description>
    <label>Docusign Access Tokens</label>
</CustomObject>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Access_Token_Part1__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Part1__c</fullName>
    <description>Access Token Part 1</description>
    <inlineHelpText>Access Token Part 1</inlineHelpText>
    <label>Access Token Part 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Access_Token_Part2__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Part2__c</fullName>
    <description>Access Token Part 2</description>
    <inlineHelpText>Access Token Part 2</inlineHelpText>
    <label>Access Token Part 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Access_Token_Part3__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Part3__c</fullName>
    <description>Access Token Part 3</description>
    <inlineHelpText>Access Token Part 3</inlineHelpText>
    <label>Access Token Part 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Access_Token_Part4__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Part4__c</fullName>
    <description>Access Token Part 4</description>
    <inlineHelpText>Access Token Part 4</inlineHelpText>
    <label>Access Token Part 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Base_Uri__c.field-meta.xml
<CustomField>
    <fullName>Base_Uri__c</fullName>
    <description>Base Uri</description>
    <inlineHelpText>Base Uri</inlineHelpText>
    <label>Base Uri</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Access_Token__c/fields/Expiry_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Expiry_DateTime__c</fullName>
    <description>Expiry DateTime</description>
    <inlineHelpText>Expiry DateTime</inlineHelpText>
    <label>Expiry DateTime</label>
    <type>DateTime</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Field_Mappings__c/Docusign_Field_Mappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Docusign Field Mappings</label>
</CustomObject>

tsr-docusign/main/default/objects/Docusign_Field_Mappings__c/fields/Sobject_Type__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type__c</fullName>
    <label>Sobject Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Field_Mappings__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Field_Mappings__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/Docusign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores docusign settings</description>
    <label>Docusign Settings</label>
</CustomObject>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <description>Stores the account id of the specified docusign account.</description>
    <inlineHelpText>Stores the account id of the specified docusign account.</inlineHelpText>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Authentication_Service__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Service__c</fullName>
    <description>The URI of the authentication service instance to be used</description>
    <inlineHelpText>The URI of the authentication service instance to be used</inlineHelpText>
    <label>Authentication Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Certificate_Label__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Label__c</fullName>
    <description>Certificate Label</description>
    <inlineHelpText>The label value of the record in Certification and Key Management</inlineHelpText>
    <label>Certificate Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Integrator_Key__c.field-meta.xml
<CustomField>
    <fullName>Integrator_Key__c</fullName>
    <description>Integrator key for the docusign account.</description>
    <inlineHelpText>Integrator key for the docusign account.</inlineHelpText>
    <label>Integrator Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/OAuth_Login__c.field-meta.xml
<CustomField>
    <fullName>OAuth_Login__c</fullName>
    <description>OAuth login url for docusign.</description>
    <inlineHelpText>OAuth login url for docusign.</inlineHelpText>
    <label>OAuth Login</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Redirect_Uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Uri__c</fullName>
    <description>Redirect Uri</description>
    <inlineHelpText>Redirect Uri</inlineHelpText>
    <label>Redirect Uri</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>The time it takes for the docusign callout to timeout.</description>
    <inlineHelpText>The time it takes for the docusign callout to timeout.</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>User Id</description>
    <inlineHelpText>User Id</inlineHelpText>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/User_Info_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>User_Info_Endpoint__c</fullName>
    <description>User info endpoint for obtaining base Uri.</description>
    <inlineHelpText>User info endpoint for obtaining base Uri.</inlineHelpText>
    <label>User Info Endpoint</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/classes/DocusignTestDataFactory.cls
@isTest
public class DocusignTestDataFactory {
    public static TREX1__App_Config__c createOrgDefaultAppConfig() {
		TREX1__App_Config__c ac = TREX1__App_Config__c.getOrgDefaults();
		ac.TREX1__Minimum_Contract_Signing_Age__c = 18;
		return ac;
	}
	
	public static Docusign_Settings__c createDocusignConfig(){
        Docusign_Settings__c config = new Docusign_Settings__c(
            Integrator_Key__c = '0fee914d-5331-4a21-87d6-dbfe1349ae7b',
            Certificate_Label__c = 'testdocusign',
            Authentication_Service__c = 'account-d.docusign.com',
            OAuth_Login__c = 'https://account-d.docusign.com/oauth/token',
            User_Id__c = 'eb28a8a4-7e32-4eda-ad70-8c02aacb48f3',
            Account_Id__c = '15898051',
            User_Info_Endpoint__c = 'https://account-d.docusign.com/oauth/userinfo',
            Redirect_Uri__c = 'https://trex-dev.my.salesforce.com/apex/DocusignCallback',
            Timeout__c = 120000
        );

        return config;
    }
	public static Docusign_Access_Token__c createAccessTokenSetting(){
        Docusign_Access_Token__c setting = new Docusign_Access_Token__c(
            Access_Token_Part1__c = 'abcdefg',
            Base_Uri__c = 'https://demo.docusign.net/restapi/v2/accounts/15898051',
            Expiry_DateTime__c = DateTime.now().addSeconds(3600)
        );

        return setting;
    }
    
	public static String getAccessToken(Docusign_Access_Token__c docusignAccessTokenSetting){
		String accessToken = docusignAccessTokenSetting.Access_Token_Part1__c;
		if(docusignAccessTokenSetting.Access_Token_Part2__c != null){
			accessToken += docusignAccessTokenSetting.Access_Token_Part2__c;
		}
		if(docusignAccessTokenSetting.Access_Token_Part3__c != null){
			accessToken += docusignAccessTokenSetting.Access_Token_Part3__c;
		}
		if(docusignAccessTokenSetting.Access_Token_Part4__c != null){
			accessToken += docusignAccessTokenSetting.Access_Token_Part4__c;
		}
		return accessToken;
	}

    public static Docusign_Field_Mappings__c createDocusignFieldMapping(){
        Docusign_Field_Mappings__c config = new Docusign_Field_Mappings__c(
        	Name = 'Contract Name',
            Data_Type__c = 'String',
            Sobject_Type__c = 'TREX1__Contract_and_Form__c',
            Source_Field__c	 = 'Name',
            Target_Field__c = 'Contract Name',
            Template_Id__c = '3843cfb1-6f19-4d6d-a4cc-cb745ddce019'
        );

        return config;
    }

    public static TREX1__Contract_or_Form_Template__c createContractTemplate() {
        return createContractTemplates(1)[0];
    }

    public static List<TREX1__Contract_or_Form_Template__c> createContractTemplates(Integer count) {
        List<TREX1__Contract_or_Form_Template__c> records =
                (List<TREX1__Contract_or_Form_Template__c>) createSObjects(TREX1__Contract_or_Form_Template__c.SObjectType, count);

        return records;
    }

    public static TREX1__Required_Contract_and_Form__c createRequiredContractForm() {
        return createRequiredContractForms(1)[0];
    }

    public static List<TREX1__Required_Contract_and_Form__c> createRequiredContractForms(Integer count) {
        List<TREX1__Required_Contract_and_Form__c> records =
                (List<TREX1__Required_Contract_and_Form__c>) createSObjects(TREX1__Required_Contract_and_Form__c.SObjectType, count);
        return records;
    }

	public static TREX1__Contract_and_Form__c createContractAndForm(){
        return createContractAndForms(1)[0];
    }

    public static List<TREX1__Contract_and_Form__c> createContractAndForms(Integer count) {
        List<TREX1__Contract_and_Form__c> records =
            (List<TREX1__Contract_and_Form__c>)createSObjects(TREX1__Contract_and_Form__c.SObjectType, count);

        for (TREX1__Contract_and_Form__c record : records) {
            record.TREX1__Valid_For__c = 'Account';
        }

        return records;
    }
	
	public static Contact createContact() {
        return createContacts(1)[0];
    }

    public static List<Contact> createContacts(Integer count) {
        List<Contact> records =
            (List<Contact>)createSObjects(Contact.SObjectType, count);

        Integer i = 0;
        for(Contact record : records) {
            record.LastName = 'test' + i++;
        }
        return records;
    }

    private static List<SObject> createSObjects(Schema.SObjectType sType, Integer num) {
        return createSObjects(sType, num, new Map<String, Object>());
    }

    private static List<sObject> createSObjects(SObjectType sType, Integer count, Map<String, Object> defaultValues) {
        List<SObject> sObjs = new List<SObject>();
        for (Integer i = 0; i < count; i++) {
            SObject newObj = sType.newSObject();
            setRecordFieldsValues(newObj, defaultValues);
            sObjs.add(newObj);
        }
        return sObjs;
    }

    public static void setRecordFieldsValues(sObject record, Map<String, Object> recordFields){
        for(String fieldName : recordFields.keySet()) {
            record.put(fieldName, recordFields.get(fieldName));
        }
    }
	
}