tsr-docusign/main/default/objects/Docusign_Settings__c/Docusign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores docusign settings</description>
    <label>Docusign Settings</label>
</CustomObject>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <description>Stores the account id of the specified docusign account.</description>
    <inlineHelpText>Stores the account id of the specified docusign account.</inlineHelpText>
    <label>Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Authentication_Service__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Service__c</fullName>
    <description>The URI of the authentication service instance to be used</description>
    <inlineHelpText>The URI of the authentication service instance to be used</inlineHelpText>
    <label>Authentication Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Certificate_Label__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Label__c</fullName>
    <description>Certificate Label</description>
    <inlineHelpText>The label value of the record in Certification and Key Management</inlineHelpText>
    <label>Certificate Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Integrator_Key__c.field-meta.xml
<CustomField>
    <fullName>Integrator_Key__c</fullName>
    <description>Integrator key for the docusign account.</description>
    <inlineHelpText>Integrator key for the docusign account.</inlineHelpText>
    <label>Integrator Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/OAuth_Login__c.field-meta.xml
<CustomField>
    <fullName>OAuth_Login__c</fullName>
    <description>OAuth login url for docusign.</description>
    <inlineHelpText>OAuth login url for docusign.</inlineHelpText>
    <label>OAuth Login</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Redirect_Uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Uri__c</fullName>
    <description>Redirect Uri</description>
    <inlineHelpText>Redirect Uri</inlineHelpText>
    <label>Redirect Uri</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>The time it takes for the docusign callout to timeout.</description>
    <inlineHelpText>The time it takes for the docusign callout to timeout.</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>User Id</description>
    <inlineHelpText>User Id</inlineHelpText>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/User_Info_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>User_Info_Endpoint__c</fullName>
    <description>User info endpoint for obtaining base Uri.</description>
    <inlineHelpText>User info endpoint for obtaining base Uri.</inlineHelpText>
    <label>User Info Endpoint</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/classes/DocusignOptions.cls
/**
 * DocusignOptions
 * @description Stores all the docusign settings that a required
 *              to make the callout to docusign.
 * @author Thomas Tran, Traction on Demand
 * @date 01-18-2017
 */
public with sharing class DocusignOptions {
	//Initial values found on the Docusign Settings (Custom Settings)
	public String integratorKey {get; set;}
	public String certificateLabel {get; set;}
	public String authenticationService {get; set;}
	public String oAuthLogin {get; set;}
	public String redirectUri {get; set;}
	public String userId {get; set;}
	public String accountId {get; set;}
	public String userInfoEndpoint {get; set;}
	public Integer timeout {get; set;}

	//Populated by callout
	public String baseURL {get; set;}
	public String returnURL {get; set;}
	public String envelopeId {get; set;}
	public String postRecipientViewURL {get; set;}

	public DocusignOptions() {
		Docusign_Settings__c settings = Docusign_Settings__c.getInstance(); 

		this.integratorKey 			= settings.Integrator_Key__c;
		this.certificateLabel 		= settings.Certificate_Label__c;
		this.authenticationService  = settings.Authentication_Service__c;
		this.oAuthLogin 			= settings.OAuth_Login__c;
		this.redirectUri 			= settings.Redirect_Uri__c;
		this.userId 				= settings.User_Id__c;
		this.accountId 				= settings.Account_Id__c;
		this.userInfoEndpoint 		= settings.User_Info_Endpoint__c;
		this.timeout       			= Integer.valueOf(settings.Timeout__c);
	}

	public Boolean validate(){
		return String.isNotBlank(integratorKey) &&
			String.isNotBlank(certificateLabel) &&
			String.isNotBlank(authenticationService) &&
			String.isNotBlank(oAuthLogin) &&
			String.isNotBlank(accountId) &&
			String.isNotBlank(userInfoEndpoint) &&
			String.isNotBlank(userId);
	} 
}