tsr-docusign/main/default/objects/Docusign_Settings__c/Docusign_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores docusign settings</description>
    <label>Docusign Settings</label>
</CustomObject>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Authentication_Service__c.field-meta.xml
<CustomField>
    <fullName>Authentication_Service__c</fullName>
    <description>The URI of the authentication service instance to be used</description>
    <inlineHelpText>The URI of the authentication service instance to be used</inlineHelpText>
    <label>Authentication Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Integrator_Key__c.field-meta.xml
<CustomField>
    <fullName>Integrator_Key__c</fullName>
    <description>Integrator key for the docusign account.</description>
    <inlineHelpText>Integrator key for the docusign account.</inlineHelpText>
    <label>Integrator Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

tsr-docusign/main/default/objects/Docusign_Settings__c/fields/Redirect_Uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Uri__c</fullName>
    <description>Redirect Uri</description>
    <inlineHelpText>Redirect Uri</inlineHelpText>
    <label>Redirect Uri</label>
    <type>Url</type>
</CustomField>

tsr-docusign/main/default/classes/DocusignConsentResultCtlr.cls
public without sharing class DocusignConsentResultCtlr {

	@AuraEnabled
	public static DocusignConfigResult getDocusignConfig(){
		DocusignConfigResult result = new DocusignConfigResult();
		Docusign_Settings__c settings = Docusign_Settings__c.getInstance(); 
		result.integratorKey = settings.Integrator_Key__c;
		result.redirectUri = settings.Redirect_Uri__c;
		result.authenticationService = settings.Authentication_Service__c;
		result.isSuccess = true;
		return result;
	}
	@AuraEnabled
	public static DocusignConfigResult checkOAuthValid(){
		DocusignConfigResult result = new DocusignConfigResult();
		
		try {
			DocusignRequest dsRequest = new DocusignRequest('GET', '', true);
			DocusignOAuth oauth = dsRequest.getOAuth();
			result.isSuccess = oauth.getAccessTokenSetting().validate() && oauth.getAccessTokenSetting().baseUri != null;
		} catch (Exception ex){
			result.isSuccess = false;
			result.errorMessage = ex.getMessage();
		}
		return result;
	}
	
	public class DocusignConfigResult{
	 	@AuraEnabled
	 	public String integratorKey {get; set;}
	 	@AuraEnabled
	 	public String redirectUri {get; set;}
	 	@AuraEnabled
	 	public String authenticationService {get; set;}
	 	@AuraEnabled
	 	public String errorMessage {get; set;}
	 	@AuraEnabled
	 	public Boolean isSuccess {get; set;}
	}

	public class DocusignException extends Exception {}

}